steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'userlogin', '--source=.','--runtime=python312' ,'--trigger-http' ,'--allow-unauthenticated' ]
options:
  logging: 'CLOUD_LOGGING_ONLY'  # Use Cloud Logging for the build logs  
